Repository vmware-tanzu/vsphere-kubernetes-drivers-operator, pull requests merged in 2021-09, with the labels that each got.

#14 Add Github Actions workflow for Build And Deploy
  .github/workflows/BuildAndDeploy.yml
  .gitignore
  Makefile
  README.md
  config/default/manager_auth_proxy_patch.yaml
  controllers/vdoconfig_controller_test.go
  hack/github-action/comp-matrix.yaml
  pkg/drivers/cpi/test_config.conf
Labels: enhancement, cla-not-required, CI/CD

#12 Support to fetch vSphere and k8s Version from k8s cluster and fetch corresponding Deployment Yamls
  README.md
  config/manager/kustomization.yaml
  controllers/vdoconfig_controller.go
  controllers/vdoconfig_controller_test.go
  go.mod
  go.sum
  pkg/session/session.go
Labels: enhancement, cla-not-required

#16 add implementation for getting CPI nodes and support for multi Datacenters
  config/manager/kustomization.yaml
  controllers/vdoconfig_controller.go
  controllers/vdoconfig_controller_test.go
  controllers/vspherecloudconfig_controller.go
  controllers/vspherecloudconfig_controller_test.go
  pkg/session/session.go
  pkg/session/session_test.go
Labels: enhancement, cla-not-required

#17 Added Support for fetching the yamls from file path and providing matrix yaml as Configmap Content
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  controllers/vdoconfig_controller.go
  controllers/vdoconfig_controller_test.go
  pkg/client/dynamic_client.go
  pkg/client/dynamic_client_test.go
Labels: cla-not-required

#19 Added Unit Test for CheckCompatAndRetrieveSpec function
  controllers/vdoconfig_controller_test.go
  controllers/vspherecloudconfig_controller_test.go
Labels: cla-not-required

#18 Add auto-upgrade feature via configMap update
  .gitignore
  controllers/vdoconfig_controller.go
  controllers/vdoconfig_controller_test.go
  main.go
Labels: cla-not-required

#20 Add Code Coverage Badge and GoReport Badge for the project
  README.md
Labels: documentation, cla-not-required

#23 Initial scaffolding for vdoctl
  Makefile
  PROJECT
  go.mod
  go.sum
  vdoctl/LICENSE
  vdoctl/cmd/compat.go
  vdoctl/cmd/configure.go
  vdoctl/cmd/creds.go
  vdoctl/cmd/deploy.go
  vdoctl/cmd/root.go
  vdoctl/cmd/store.go
  vdoctl/cmd/vc.go
  vdoctl/main.go
Labels: cla-not-required

#26 Modifies README and adds Getting Started doc.
  Makefile
  README.md
  artifacts/vdo-spec.yaml
  docs/getting-started.md
  docs/vdo-topology.png
  hack/deploy-vdo-cluster.sh
Labels: documentation, cla-not-required

#28 Adds support to install operator on CRC clusters with OLM integration
  Makefile
  artifacts/openshift/crd.yaml
  artifacts/openshift/rbac.yaml
  artifacts/openshift/vsphere-kubernetes-drivers-operator.clusterserviceversion.yaml
  artifacts/vanilla/vdo-spec.yaml
  artifacts/vdo-spec.yaml
  config/manifests/bases/vsphere-kubernetes-drivers-operator.clusterserviceversion.yaml
  config/openshift/csv/kustomization.yaml
  config/openshift/csv/vsphere-kubernetes-drivers-operator.clusterserviceversion.yaml
  config/openshift/misc/catalog_source.yaml
  config/openshift/misc/operator-group.yaml
  config/openshift/rbac/kustomization.yaml
  config/openshift/rbac/rbac.yaml
  config/rbac/kustomization.yaml
  docs/getting-started.md
  hack/deploy-vdo-cluster.sh
Labels: enhancement, cla-not-required

#34 add vdo deploy cmd
  vdoctl/cmd/deploy.go
  vdoctl/cmd/root.go
Labels: cla-not-required

#37 add tests for session functions
  pkg/client/dynamic_client_test.go
  pkg/client/dynclient_suite_test.go
  pkg/session/session.go
  pkg/session/session_suite_test.go
  pkg/session/session_test.go
Labels: cla-not-required

#38 Add update cmd to vdoctl
  .github/workflows/BuildAndDeploy.yml
  .gitignore
  vdoctl/cmd/update.go
  vdoctl/cmd/update_matrix.go
Labels: enhancement, cla-not-required

#35 Add VDO configuration support using command line interface
  api/v1alpha1/vdoconfig_types.go
  config/crd/bases/vdo.vmware.com_vdoconfigs.yaml
  config/manager/kustomization.yaml
  go.mod
  go.sum
  pkg/session/session.go
  vdoctl/cmd/compat.go
  vdoctl/cmd/configure.go
  vdoctl/cmd/drivers.go
  vdoctl/cmd/vc.go
  vdoctl/pkg/utils/promptutil.go
Labels: cla-not-required, update-vdoctl-documentation

#39 Add vdoctl status command for fetching VDO Status
  go.sum
  vdoctl/cmd/root.go
  vdoctl/cmd/status.go
Labels: enhancement, cla-not-required

#43 Add arch link in the main README
  README.md
  docs/architecture/README.md
  docs/architecture/vdo-architecture.md
Labels: documentation, cla-not-required

#44 Update the Architecture with correct links
  docs/architecture/vdo-architecture.md
Labels: documentation, cla-not-required

#42 Fix reconcile issue for upgrade scenario
  controllers/vdoconfig_controller.go
  controllers/vdoconfig_controller_test.go
  pkg/client/dynamic_client.go
  pkg/client/dynamic_client_test.go
  vdoctl/cmd/deploy.go
  vdoctl/cmd/update_matrix.go
Labels: bug, cla-not-required
