Repository vmware-tanzu/vsphere-kubernetes-drivers-operator, pull requests merged in 2021-12, with the labels that each got.

#96 Fix vdoctl to avoid KUBECONFIG check on invocation of help command
  vdoctl/cmd/root.go
Labels: enhancement, cla-not-required

#106 Use the current namespace instead of hardcoded ones
  artifacts/vanilla/vdo-spec.yaml
  config/manager/manager.yaml
  controllers/vdoconfig_controller.go
  controllers/vdoconfig_controller_test.go
Labels: bug, cla-not-required

#101 Fix usage of update command provided in the example field
  vdoctl/cmd/update.go
  vdoctl/cmd/update_matrix.go
Labels: cla-not-required

#107 Use current namespace of VdoController in vdoctl
  controllers/vdoconfig_controller_test.go
  vdoctl/cmd/configure_matrix.go
  vdoctl/cmd/delete.go
  vdoctl/cmd/drivers.go
  vdoctl/cmd/root.go
  vdoctl/cmd/status.go
  vdoctl/cmd/update_matrix.go
  vdoctl/cmd/version.go
Labels: bug, cla-not-required

#113 Adds code to replace kubelet path in csi daemonset spec
  controllers/vdoconfig_controller.go
  controllers/vdoconfig_controller_test.go
Labels: cla-not-required

#110 Add the Developer Guide for VDO
  docs/developer-guide.md
Labels: documentation, cla-not-required

#109 Display messages for configure,update and delete command.
  vdoctl/cmd/configure_matrix.go
  vdoctl/cmd/delete.go
  vdoctl/cmd/delete_vdo.go
  vdoctl/cmd/update_matrix.go
Labels: enhancement, cla-not-required

#120 Adding support for vmware-system-csi namespace creation
  artifacts/openshift/rbac.yaml
  artifacts/vanilla/vdo-spec.yaml
  config/manager/kustomization.yaml
  config/openshift/rbac/rbac.yaml
  config/rbac/role.yaml
  controllers/vdoconfig_controller.go
Labels: cla-not-required

#111 Update the documents with pre-requisite for CPI and local file path syntax.
  docs/configure_drivers.md
  docs/getting-started.md
Labels: documentation, cla-not-required

#87 Fix for compatibility issues when CPI is not configured
  controllers/vdoconfig_controller.go
  controllers/vdoconfig_controller_test.go
Labels: cla-not-required

#115 Add oc-certification artifacts and update makefile
  .gitignore
  Makefile
  artifacts/oc-certified/0.1.0/manifests/vdo-controller-manager-metrics-service-rbac.yaml
  artifacts/oc-certified/0.1.0/manifests/vdoconfigs.vdo.vmware.com-crd.yaml
  artifacts/oc-certified/0.1.0/manifests/vsphere-kubernetes-drivers-operator.clusterserviceversion.yaml
  artifacts/oc-certified/0.1.0/manifests/vspherecloudconfigs.vdo.vmware.com-crd.yaml
  artifacts/oc-certified/0.1.0/metadata/annotations.yaml
  artifacts/oc-certified/ci.yaml
  artifacts/openshift/rbac.yaml
  config/openshift/crd/vdoconfigs.vdo.vmware.com-crd.yaml
  config/openshift/crd/vspherecloudconfigs.vdo.vmware.com-crd.yaml
  config/openshift/csv/kustomization.yaml
  config/openshift/csv/vsphere-kubernetes-drivers-operator.clusterserviceversion.yaml
  config/openshift/rbac/vdo-controller-manager-metrics-service.yaml
Labels: cla-not-required, certification

#122 Update the vdo-spec.yaml with new harbor image
  artifacts/vanilla/vdo-spec.yaml
Labels: cla-not-required

#126 Adds kubelet path replacement for DRIVER_REG_SOCK_PATH environment variable
  controllers/vdoconfig_controller.go
  controllers/vdoconfig_controller_test.go
Labels: cla-not-required

#129 updating docs with vdoctl configure drivers command
  docs/configure_drivers.md
Labels: cla-not-required

#134 Replaces kubelet path in liveness probe. This is observed in csi 2.4+
  controllers/vdoconfig_controller.go
  controllers/vdoconfig_controller_test.go
Labels: cla-not-required

#118 Support configuration of default compatibility matrix if matrix is not configured before configuring drivers
  vdoctl/cmd/configure_matrix.go
  vdoctl/cmd/delete_vdo.go
  vdoctl/cmd/deploy.go
  vdoctl/cmd/drivers.go
  vdoctl/cmd/root.go
  vdoctl/cmd/status.go
  vdoctl/cmd/update_matrix.go
  vdoctl/cmd/version.go
Labels: enhancement, cla-not-required

#124 Getting started from release Guide
  docs/getting-started.md
  docs/getting-started/getting-started-from-release.md
  docs/images/vdo-user-flow.png
Labels: documentation, cla-not-required
