Repository vmware-tanzu/vsphere-kubernetes-drivers-operator, pull requests merged in 2022-01, with the labels that each got.

#135 Update "use-csinode-id" key in the internal-feature-states.csi.vsphere.vmware.com config map
  controllers/vdoconfig_controller.go
  controllers/vdoconfig_controller_test.go
Labels: enhancement, cla-not-required

#137 adding support and validation for providing FQDN
  vdoctl/cmd/drivers.go
  vdoctl/pkg/utils/promptutil.go
Labels: cla-not-required

#138 Update docs with default compat matrix details
  Makefile
  artifacts/vanilla/vdo-spec.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/manager/controller_manager_config.yaml
  config/vanilla_k8s/compat_matrix_configmap.yaml
  config/vanilla_k8s/kustomization.yaml
  docs/getting-started/configure_drivers.md
  docs/getting-started/getting-started-from-release.md
  docs/getting-started/getting-started-via-code.md
Labels: documentation, cla-not-required

#140 Update the documents with taint as pre-requisite
  controllers/vdoconfig_controller.go
  docs/getting-started.md
Labels: documentation, cla-not-required
